### ISSUE TITLE
Change name

### ISSUE THREAD

**Issue by chessai** [andrewthad/error-codes#1]
I wouldn't call this library `error-codes`. It just provides posix error codes, so the name is ambiguous. error codes as a convention extend well beyond posix

**Comment by andrewthad** [comment]
This probably wasn't clear since this library is totally undocumented, but the scope of this library isn't POSIX error codes. It's whatever [`Foreign.C.Error`](http://hackage.haskell.org/package/base-4.12.0.0/docs/Foreign-C-Error.html) has. For example `ESOCKTNOSUPPORT` is not specified by `POSIX`. Neither is `ESRMNT`.

One thing I haven't checked is how many problematic error code overlaps there are. Linux has `EWOULDBLOCK` and `EAGAIN` as the same value, but that's fine. I'm not sure how many Linux-specific or Windows-specific codes there are in here that overlap in a misleading way. CPP would be needed to fix this. But then again, the only purpose of this library is to help other libraries present unexpected error codes in a more user-friendly way (currently I'm only using this in `sockets`). The human-readable description should be presented along with, not in place of, the numeric value, so getting the description wrong isn't that bad.

**Comment by chessai** [comment]
Ah ok. The name is still misfitting though, in that case

**Comment by chessai** [comment]
Changed my mind.
